### ISSUE TITLE
`@only_one` block is executed by a single iteration (not a single task)

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaFolds2/OhMyThreads.jl#100]
From my understanding of the docstring
```
  @only_one begin ... end

  This can be used inside a @tasks for ... end block to mark a region of code to be executed by only one
  of the parallel tasks (all other tasks skip over this region).
```
I was expecting
```julia
@tasks for i in 1:8
    @set ntasks = 2

    println(i, ": before")
    @only_one begin
        println(i, ": after")
    end
end
```
to print after 4 times (since a single task has to run 4 iterations of the loop).  Instead, I get the output
```
5: before
1: before
5: after
6: before
2: before
7: before
8: before
3: before
4: before
```
Is this expected? Should the docstring be changed or I just got it wrong? It seems to me that this macro should be called `@only_once` instead.

**Comment by carstenbauer** [comment]
This was indeed a bug. I committed a fix (to master). Feel free to try it out.
