### ISSUE TITLE
GreedyScheduler with `ntasks` and `chunksize` given errors

### ISSUE THREAD

**Issue by fredrikekre** [JuliaFolds2/OhMyThreads.jl#120]
```
julia> GreedyScheduler(; ntasks = 4, chunksize = 10)
ERROR: ArgumentError: nchunks and chunksize are mutually exclusive and only one of them may be a positive integer
```

**Comment by carstenbauer** [comment]
`ntasks` == `nchunks` but we should improve the message

**Comment by fredrikekre** [comment]
> ntasks == nchunks

Why this restriction? It looks like `nchunks` is just set erroneously here: https://github.com/JuliaFolds2/OhMyThreads.jl/blob/8ea0ff7e415552f8edfc83d66fe9928be21231f0/src/schedulers.jl#L282 ?

**Comment by carstenbauer** [comment]
I'm sorry, my comment was wrong. We used to have `nchunks` for all schedulers in the past and there it was `== ntasks` because we spawn one task per chunk. For the greedy scheduler, this isn't the case, of course.
