### ISSUE TITLE
thread based `sort` ?

### ISSUE THREAD

**Issue by longemen3000** [JuliaFolds2/OhMyThreads.jl#16]
related: https://chapel-lang.org/blog/posts/std-sort-performance/

**Comment by carstenbauer** [comment]
IMO, this shouldn't be a focus. Maybe this would also be better placed in https://github.com/JuliaCollections/SortingAlgorithms.jl or elsewhere.

**Comment by MasonProtter** [comment]
I think it's not a totally unreasonable thing to put in here if someone wants to write the algorithm, but I agree it's not really something I'd focus on personally.

**Comment by carstenbauer** [comment]
This won't be our focus any time soon, if at all, which is why I'm closing this.
