### ISSUE TITLE
Make scheduler options `struct`s

### ISSUE THREAD

**Issue by carstenbauer** [JuliaFolds2/OhMyThreads.jl#22]
* For `schedule=:static` the reasonable default is `nchunks=nthreads()`.
* For `schedule=:dynamic` the reasonable default is `nchunks=x*nthreads()`, where `x` is a small factor (maybe 2 or 3).
  * With the current default (`nchunks=nthreads()`) we have no load balancing and we're no better than `@threads :dynamic`.
* I haven't tested / thought about `schedule=:greedy` yet.

**Comment by carstenbauer** [comment]
See e.g. `https://juliafolds2.github.io/OhMyThreads.jl/dev/examples/juliaset/juliaset/` for an example

**Comment by MasonProtter** [comment]
Yeah, I was thinking that with all of these different options and the way they depend on eachother, I'd want to make the schedule a `struct`. i.e. something like
```
Base.@kwdef struct GreedyScheduler
    nchunks::Int = nthreads()
    split::Symbol=:batch
end
```

**Comment by carstenbauer** [comment]
Might make sense, yes.
