### ISSUE TITLE
Rename `@init` to `@tasklocal` or `@local`, make `@set init` set the `init` kwarg

### ISSUE THREAD

**Issue by MasonProtter** [JuliaFolds2/OhMyThreads.jl#64]
I just realized that in `@tasks`, we 

1) have no way to set the `init` keyword argument
2) the obvious way to do that would be with `@init` or `@set init = ...`, but that seems unnececarily confusing given that we also have `@init` for task local values.

Given that, I think it'd be good to do a renaming here before too many people start relying on `@tasks`. Any thoughts?

**Comment by carstenbauer** [comment]
Good point. I vote for `@init -> @local`. Technically that's a breaking change (although we only introduced `@init` a few days ago...) but I don't want to tag a breaking release just for renaming this. Maybe only deprecate it for now and then drop it in the next breaking release?

**Comment by MasonProtter** [comment]
I think if we deprecate it, then it'll still encourage people to use it, because the only time most people use julia with deprecation warnings enabled is inside a package.

**Comment by MasonProtter** [comment]
I'm not sure there's really any downside to tagging a breaking release since this package is young and we haven't made a big announcement of it yet.

**Comment by carstenbauer** [comment]
Maybe you're right. We should then drop SpawnAllScheduler in this release, which is marked as deprecated.
