### ISSUE TITLE
Option to turn off multithreading

### ISSUE THREAD

**Issue by carstenbauer** [JuliaFolds2/OhMyThreads.jl#69]
Inspired by https://discourse.julialang.org/t/conditional-multithreading/32421

**Comment by MasonProtter** [comment]
Yeah, I think the design here should favour the non-multithreaded path via a non-inlined function barrier, i.e. something like
```
function tmapreduce(f, op, itr; enable::Bool=true, kwargs...)
     if enable
        @noinline _tmapreduce(f, op, itr; kwargs...)
    else
        mapreduce(f, op, itr)
    end
end
```
